Zamat\Bundle\OAuth2ServerBundle\Entity\AccessToken:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2ServerBundle\Entity\Repository\AccessTokenRepository 
    table: zamat_oauth_access_token
    id:
        token:
            type:       string
            length:     40
    fields:
        expires:
            type:       datetime
        scope:
            type:       string
            length:     50
            nullable:   true
    manyToOne:
      client:
        targetEntity: \Zamat\Bundle\OAuth2ServerBundle\Entity\Client
        joinColumn:
          name: client_id
          referencedColumnName: client_id
          onDelete: CASCADE
          onUpdate: CASCADE
      user:
        targetEntity: \Zamat\Bundle\OAuth2ServerBundle\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: id
          nullable: TRUE
          onDelete: CASCADE
          onUpdate: CASCADE     
    lifecycleCallbacks: {  }
