Zamat\Bundle\OAuth2ServerBundle\Entity\AuthorizationCode:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2ServerBundle\Entity\Repository\AuthorizationCodeRepository  
    table: zamat_oauth_authorization_code
    id:
        code:
            type:       string
            length:     40
    fields:
        expires:
            type:       datetime
        redirect_uri:
            type:       simple_array
        scope:
            type:       string
            length:     255
            nullable:   true
    manyToOne:
      client:
        targetEntity: \Zamat\Bundle\OAuth2ServerBundle\Entity\Client
        joinColumn:
          name: client_id
          referencedColumnName: client_id
          onDelete: CASCADE
          onUpdate: CASCADE
      user:
        targetEntity: \Zamat\Bundle\OAuth2ServerBundle\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
          onUpdate: CASCADE        
    lifecycleCallbacks: {  }
