Zamat\Bundle\OAuth2ServerBundle\Entity\ClientPublicKey:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2ServerBundle\Entity\Repository\ClientPublicKeyRepository  
    table: zamat_oauth_client_public_key
    id:
        client_id:
            type:       string
            length:     50
    fields:
        public_key:
            type:       text
    oneToOne:
      client:
        targetEntity: \Zamat\Bundle\OAuth2ServerBundle\Entity\Client
        joinColumn:
          name: client_id
          referencedColumnName: client_id
          onDelete: CASCADE
          onUpdate: CASCADE
    lifecycleCallbacks: {  }
