Zamat\Bundle\OAuth2ServerBundle\Entity\Client:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2ServerBundle\Entity\Repository\ClientRepository 
    table: zamat_oauth_client
    id:
        client_id:
            type:       string
            length:     50
    fields:
        client_secret:
            type:       string
            length:     40
            nullable:   true
        redirect_uri:
            type:       simple_array
        grant_types:
            type:       simple_array
            nullable:   true
        scopes:
            type:       simple_array
            nullable:   true
    lifecycleCallbacks: {  }
