Zamat\Bundle\OAuth2ServerBundle\Entity\User:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2ServerBundle\Entity\Repository\UserRepository 
    table: zamat_oauth_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type:       string
            length:     255
            nullable:   false
        email:
            type:       string
            length:     255
            nullable:   false
        password:
            type:       string
            length:     255
            nullable:   false
        isActive:
            type:       boolean
            nullable:   false          
    lifecycleCallbacks: {  }
